### ISSUE TITLE
UIButton: wrong results on .sizeToFit with contentEdgeInsets

### ISSUE THREAD

**Issue by dillidon** [layoutBox/PinLayout#142]
Setting 'contentEdgeInsets' for UIButton is not take effect on '.sizeToFit' with any parameters. Please correct this.

**Comment by lucdion** [comment]
@dillidon PinLayout simply calls `UIButton.sizeThatFits(:CGSize)` to determine the final size of the button. It can only be an issue with the UIButton `sizeThatFits` method returning a size that doesn't respect its contentEdgeInsets. Could you validate that if you call directly `button.sizeThatFits(CGSize(...)` you receive the right size?

**Comment by dillidon** [comment]
@lucdion no)

**Comment by lucdion** [comment]
Two solutions:
1. You implement a class InsetsButton that inherits from UIButton, in that class you implement a method `sizeThatFits` method that returns a size including the contentEdgeInsets.
2. You call `button.sizeThatFits(CGSize(...)` and you adjust yourself the insets. See code below.

```
let size = button.sizeThatFits(CGSize(width: 400, height: .greatestFiniteMagnitude)) 
button.pin.width(size.width + insets.left + insets.right).height(size.height + insets.top + insets.bottom) 
```

Solution 1 is much nicer. Anyway, you're probably going to use that button often in your app.

**Comment by dillidon** [comment]
@lucdion thanks)
