### ISSUE TITLE
Layout group of views

### ISSUE THREAD

**Issue by dillidon** [layoutBox/PinLayout#144]
Hi! Could not add the possibility of changing views at once for the whole group, as `Stack View`. 

I'm tired of trying to sort through all possible combinations of methods in the `FlexLayout`. 
The task is simple at first glance:

<img width="347" alt="2018-06-07 16 17 58" src="https://user-images.githubusercontent.com/7115804/41102216-05032762-6a6f-11e8-8385-f74679cf586b.png">

As a result, I again returned to a clean `PinLayout`.

It would be great to add views to the main view and write the following code:

``` swift
cardView.add(bigTitle, blurView)
blurView.contentView.add(price, textView)
textView.add(title, subtitle)

card.pin.stack(axis: .vertical, alignment: .fill, distribution: .equalSpacing) {
  bigTitle.pin.inset(20).sizeToFit(.width, .heightFlexible).maxHeight(50%)
  blurView.stack(axis: .horizontal, alignment: .center, distribution: .equalSpacing, spacing: 4, inset: 20) {
    price.pin.height(28).maxWidth(50%).sizeToFit(.widthFlexible).priority(.highest)
    textView.pin.stack(axis: .vertical, alignment: .fill, distribution: .fillEqually, spacing: 2)
  }
}
```

**Comment by enricenrich** [comment]
Any update on this? Would be really helpful.

**Comment by lucdion** [comment]
Hi @dillidon @enricenrich, creating a stackview it is quite complex, and currently, I didn't want to add this complexity and high-level API to PinLayout. That's why I started another project **StackViewLayout** (https://github.com/layoutBox/StackViewLayout/tree/dev), the project is 95% complete, but I didn't have enough time to complete it. The API is inspired by flexbox.

**Comment by enricenrich** [comment]
Thanks for the update @lucdion!

**Comment by lalawue** [comment]
> Hi! Could not add the possibility of changing views at once for the whole group, as `Stack View`.
> 
> I'm tired of trying to sort through all possible combinations of methods in the `FlexLayout`.
> The task is simple at first glance:
> 
> <img alt="2018-06-07 16 17 58" width="347" src="https://user-images.githubusercontent.com/7115804/41102216-05032762-6a6f-11e8-8385-f74679cf586b.png">
> 
> As a result, I again returned to a clean `PinLayout`.
> 
> It would be great to add views to the main view and write the following code:
> 
> ```swift
> cardView.add(bigTitle, blurView)
> blurView.contentView.add(price, textView)
> textView.add(title, subtitle)
> 
> card.pin.stack(axis: .vertical, alignment: .fill, distribution: .equalSpacing) {
>   bigTitle.pin.inset(20).sizeToFit(.width, .heightFlexible).maxHeight(50%)
>   blurView.stack(axis: .horizontal, alignment: .center, distribution: .equalSpacing, spacing: 4, inset: 20) {
>     price.pin.height(28).maxWidth(50%).sizeToFit(.widthFlexible).priority(.highest)
>     textView.pin.stack(axis: .vertical, alignment: .fill, distribution: .fillEqually, spacing: 2)
>   }
> },
> ```

I wrote a PinStackView relies on PinLayout in https://github.com/lalawue/PinStackView, you can take a try.

**Comment by lucdion** [comment]
Very old topic. Closing it, sorry

**Comment by lalawue** [comment]
> Hi! Could not add the possibility of changing views at once for the whole group, as `Stack View`.
> 
> I'm tired of trying to sort through all possible combinations of methods in the `FlexLayout`. The task is simple at first glance:
> 
> <img alt="2018-06-07 16 17 58" width="347" src="https://user-images.githubusercontent.com/7115804/41102216-05032762-6a6f-11e8-8385-f74679cf586b.png">
> 
> As a result, I again returned to a clean `PinLayout`.
> 
> It would be great to add views to the main view and write the following code:
> 
> ```swift
> cardView.add(bigTitle, blurView)
> blurView.contentView.add(price, textView)
> textView.add(title, subtitle)
> 
> card.pin.stack(axis: .vertical, alignment: .fill, distribution: .equalSpacing) {
>   bigTitle.pin.inset(20).sizeToFit(.width, .heightFlexible).maxHeight(50%)
>   blurView.stack(axis: .horizontal, alignment: .center, distribution: .equalSpacing, spacing: 4, inset: 20) {
>     price.pin.height(28).maxWidth(50%).sizeToFit(.widthFlexible).priority(.highest)
>     textView.pin.stack(axis: .vertical, alignment: .fill, distribution: .fillEqually, spacing: 2)
>   }
> }
> ```

Hi, May be you can try this: https://github.com/lalawue/PinStackView
