### ISSUE TITLE
SafeArea within UITabBarController

### ISSUE THREAD

**Issue by VincentSit** [layoutBox/PinLayout#154]
Thanks for such a great library! I have been using it for a while in my project. I have a question about the SafeArea.

When we build the interface, we usually don't overwrite the `loadview` method. If we move the code inside the [`SafeAreaView`](https://github.com/layoutBox/PinLayout/blob/master/Example/PinLayoutSample/UI/Examples/SafeArea/SafeAreaView.swift) to [`SafeAreaViewController`](https://github.com/layoutBox/PinLayout/blob/master/Example/PinLayoutSample/UI/Examples/SafeArea/SafeAreaViewController.swift) in the [Example project](https://github.com/layoutBox/PinLayout/tree/master/Example), the SafeArea will be invalid and the layout will not meet expectations. 

This is also the problem that I am facing now. My project is a Tabbed app like the Clock app of iOS, and most of the view controllers are managed by UITabBarController. I have a problem with SafeArea when laying out the views.

I want to build the interface directly in the view controller instead of creating a separate view for each view controller, and then overriding its `loadview` method, which is obviously a bit cumbersome. I tried to solve it but did not find a good solution. 

So I would like to ask any suggestions? Is overriding `loadview` the only solution?

[PinLayoutSafeAreaDemo.zip](https://github.com/layoutBox/PinLayout/files/2164111/PinLayoutSafeAreaDemo.zip)

![pinlayout-1](https://user-images.githubusercontent.com/4084679/42290147-15c913a8-7ff6-11e8-90c9-bbd5d2296763.jpg)

**Comment by lucdion** [comment]
Hi @VincentSit, you need to layout your views inside `viewDidLayoutSubviews()`.  
I've updated your demo example with the following code and see the result below:

``` 
class FirstViewController: UIViewController {
    let aView = UIView()
    let bView = UIView()
    let cView = UIView()
    
    override func viewDidLoad() {
        super.viewDidLoad()

        aView.backgroundColor = .red
        view.addSubview(aView)

        bView.backgroundColor = .blue
        view.addSubview(bView)

        cView.backgroundColor = .yellow
        view.addSubview(cView)
    }

    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()

        aView.pin.horizontally(10).top(view.pin.safeArea.top).height(40)
        bView.pin.horizontally(30).top(view.pin.safeArea.top + 10).height(40)
        cView.pin.horizontally(50).bottom(view.pin.safeArea.bottom).height(40)
    }
}
```

![image](https://user-images.githubusercontent.com/14981341/42291411-6d0a4090-7f99-11e8-9977-fa4382698504.png)

**Comment by VincentSit** [comment]
@lucdion Thank you for your quick response, it works. I think I made a stupid mistake and forgot to try this method. BTW, this library is really really great, and it solves the pain points I used AutoLayout over the past few years. I want to buy you a cup of coffee but  I didn't find the donate button.

**Comment by lucdion** [comment]
Thanks @VincentSit for this nice comment, it is appreciated 😀
