### ISSUE TITLE
Make view public in PinLayout<View: Layoutable> class

### ISSUE THREAD

**Issue by peymankh** [layoutBox/PinLayout#155]
This is particularly useful when some clients may need to provide a custom implementation for some cases and need access to the view object when extending.

**Comment by lucdion** [comment]
@peymankh would you give me an example of custom implementation, so I could add its support and add a unit test for it?

**Comment by lucdion** [comment]
ping @peymankh ⬆️ 🙂

**Comment by peymankh** [comment]
Hi @lucdion,

In general the ability to be able to add extensions to PinLayout is great.

An example would be:

```
protocol ContainerViewProtocol: class {
    associatedType Content: UIView
    var contentView: Content { get }
}

extension PinLayout where View: ContainerViewProtocol {
    public func sizeToFitByWidth() -> PinLayout {
        self.contentView.pin
            .top()
            .horizontally()
            .sizeToFit(.width)

        return self.pin.height(self.contentView.frame.maxY)
    }

    public func sizeToFitByHeight() -> PinLayout {
        self.contentView.pin
            .left()
            .vertically()
            .sizeToFit(.height)

        return self.pin.height(self.contentView.frame.maxX)
    }
}
```

**Comment by lucdion** [comment]
Hi @peymankh, even with `view` public, you won't be able to use this kind of extensions. `view` is not an UIView anymore, but an instance of a class that implement the protocol `Layoutable`.

Please try to modify PinLayout locally and see what you can to around this. 
If at the end you have a proposition, don't hesitate to contact me.

**Comment by lucdion** [comment]
No feedback for a long period.
