### ISSUE TITLE
Consider adding the offset parameter to Anchor.

### ISSUE THREAD

**Issue by VincentSit** [layoutBox/PinLayout#157]
For example:

from
```
view.pin.bottom(10).left(10)
```
to
```
view.pin.bottomLeft(10)
```

I have another question, for example, I have a button that has an image, obviously it has an intrinsic size, but if I only specify its origin when laying out, it won't show because the size is 0. My current approach is to manually call `sizeToFit()` to set its size when it is initialized, or to hardcode its size during layout. `pin.sizeToFit(.xxx)` does not correctly set its size. These approach is obviously not elegant enough, I wonder if I can automatically use its intrinsic size like AutoLayout.

**Comment by lucdion** [comment]
1) I take note of your proposition. That would makes sense. Until then you can also do `view.pin. bottomLeft().margin(10)`. 
2) I will submit a PR today that adds a method `sizeToFit()` that does just that. Ex: `view.pin.center().sizeToFit()`

**Comment by VincentSit** [comment]
Thank you, I have not tried bottomLeft().`margin(10)` before.

**Comment by lucdion** [comment]
@VincentSit `sizeToFit()` is now available.

**Comment by VincentSit** [comment]
@lucdion Nice work, thank you!

**Comment by lucdion** [comment]
PR https://github.com/layoutBox/PinLayout/pull/163

**Comment by VincentSit** [comment]
Great! Thank you. @lucdion

**Comment by lucdion** [comment]
Implemented in the Release 1.7.11: https://github.com/layoutBox/PinLayout/releases/tag/1.7.11
