### ISSUE TITLE
Animation example?

### ISSUE THREAD

**Issue by Aranoledur** [layoutBox/PinLayout#159]
Hi! I'm looking forward to switch _in code layout_ to PinLayout, but I have a concern about animations. So do you have some animation example in PinLayout? Like, how to reset pin rules after a tap and animate them?

**Comment by lucdion** [comment]
Hi @Aranoledur.

First of all, there is no such thing as reset pin rules. PinLayout is completely stateless, layout always start from the view's current frame and apply pin methods.

`view.pin.top(30)` only change the view's top position, keeping its size and its horizontal position.

You're right that I should add an animation sample, I'll do that shortly and I will also add a section in the documentation. For now, the number of strategies to use is endless, its pretty a question of preferences. I can demonstrate some of them.

All examples below animate the appearance of an UIImageView.

**1- Basic: Using UIView.setNeedsLayout + UIView.layoutIfNeeded.**

```
var isImageVisible = false

func layoutSubviews() {
   super.layoutSubviews()

   let imageLeftPosition = isImageVisible ? 0 : -imageView.frame.width
   imageView.pin.left(imageLeftPosition).vCenter() 
   ...
}

func didTapTogglemage() {
   UIView.animate(withDuration: 0.2) { 
         self.isImageVisible = !self.isImageVisible
         self.setNeedsLayout()
         self.layoutIfNeeded()
    }
}
```

**2- Using a layout method.**

```
var isImageVisible = false

func layoutSubviews() {
   super.layoutSubviews()
   layoutImageView()
   ...
}

func layoutImageView() {
   let imageLeftPosition = isImageVisible ? 0 : -imageView.frame.width
   imageView.pin.left(imageLeftPosition).vCenter() 
}

func didTapTogglemage() {
   UIView.animate(withDuration: 0.2) { 
         self.isImageVisible = !self.isImageVisible
         self.layoutImageView()
    }
}
```

**3- Using a state and having multiple separates layout methods.**

```
enum State {
   case initial
   case imageVisible
}
var state = State.initial

func layoutSubviews() {
   super.layoutSubviews()

   switch state {
   case .initial: layoutInitialState()
   case .imageVisible: layoutImageVisibleState()
   }
}

func layoutInitialState() {
   imageView.pin.left(-imageView.frame.width).vCenter() 
   ...
}

func layoutImageVisibleState() {
   imageView.pin.left(0).vCenter() 
   ...
}
```

**Comment by Aranoledur** [comment]
Hm, okey, thanks. I was thinking of PinLayout as a set of rules that is applied to frames. Now I get it :)

**Comment by lucdion** [comment]
PinLayout is more a set of methods that update view's frame.

**Comment by lucdion** [comment]
@Aranoledur I've finally added a section related to animations using PinLayout: https://github.com/layoutBox/PinLayout#animations

**Comment by Aranoledur** [comment]
Thanks! You’re awesome
