### ISSUE TITLE
Can it be used with UIViews added on storyboard?

### ISSUE THREAD

**Issue by netgfx** [layoutBox/PinLayout#161]
I have some UIViews created on storyboard, and I want to add subviews into them and layout those subviews (UILabel, UIButton, etc) using PinLayout, I have override `self.viewWillLayoutSubviews()`

But the subviews won't appear, so I'm wondering if it is possible at all.

Thanks!

**Comment by VincentSit** [comment]
Hi @netgfx, I think PinLayout supports SB, and there is no difference between pure code and SB. I made a simple demo for you, download and checkout it.

[PinLayoutWithSB.zip](https://github.com/layoutBox/PinLayout/files/2250286/PinLayoutWithSB.zip)

**Comment by netgfx** [comment]
thanks for the sample. I will try it again and let you know.

**Comment by netgfx** [comment]
Works, also that `Then` lib helped! Thanks!
