### ISSUE TITLE
I can not figure out how to build a complex layout.

### ISSUE THREAD

**Issue by sLm-s** [layoutBox/PinLayout#162]
Hi @lucdion . Tell me how to create such a layout? some labels can be hidden. In some cases, a button may appear and move everything to the top except for the image. The height of the cell is set. The layout is made on the FlexLayout. But I do not understand how to do it in a PinLayout.

`rootContainer.flex.direction(.row).padding(4).grow(1).shrink(1).define { (flex) in

            flex.addItem(imageProduct).height(itemSize.height - 8).width(itemSize.height - 20)

            flex.addItem().grow(1).shrink(1).justifyContent(.spaceBetween).marginHorizontal(8).define({ (flex) in

                flex.addItem(labelContainer).shrink(1).grow(1).define { (flex) in
                    flex.addItem(shortName).shrink(1)
                    flex.addItem(valueFirst).marginTop(2).shrink(2)
                    flex.addItem(valueSecond).shrink(2)

                    flex.addItem(containerStars).direction(.row).marginTop(4).alignSelf(.start).alignItems(.center).define({ (flex) in
                        flex.addItem(imageStar1).size(10)
                        flex.addItem(imageStar2).marginLeft(2).size(10)
                        flex.addItem(imageStar3).marginLeft(2).size(10)
                        flex.addItem(imageStar4).marginLeft(2).size(10)
                        flex.addItem(imageStar5).marginLeft(2).size(10)
                        flex.addItem(countReviews).marginLeft(4)
                    })
                }

                flex.addItem().define({ (flex) in

                    flex.addItem().define({ (flex) in

                        flex.addItem().direction(.row).justifyContent(.spaceBetween).define { (flex) in

                            flex.addItem().alignSelf(.end).define { (flex) in
                                flex.addItem(priceLabel)
                                flex.addItem(priceDiscount)
                            }

                            flex.addItem().alignItems(.end).alignSelf(.end).define({ (flex) in
                                flex.addItem(textOrder)
                                flex.addItem(deliveryDayLabel)
                            })
                        }

                    })

                    flex.addItem(showActivationDate).shrink(1)
                    flex.addItem(notProduct).shrink(1)
                    flex.addItem(selectGiftButton).height(20).alignSelf(.center).marginTop(4).shrink(1)
                })

            })

        }`

![simulator screen shot - iphone 8 - 2018-08-02 at 13 48 50](https://user-images.githubusercontent.com/20534572/43571650-5457628a-965f-11e8-9262-729b41dfdae6.png)

![simulator screen shot - iphone se - 2018-08-02 at 15 11 50](https://user-images.githubusercontent.com/20534572/43574853-09e406a6-9667-11e8-8351-88db56d337b4.png)
![simulator screen shot - iphone se - 2018-08-02 at 15 10 27](https://user-images.githubusercontent.com/20534572/43574855-0a082144-9667-11e8-9cdb-9d392a35525e.png)

**Comment by lucdion** [comment]
Hi @sLm-s, could you share me your PinLayout source code, I could pinpoint your issue.

**Comment by sLm-s** [comment]
I created an approximate project where there is an example of FlexLayout and PinLayout. Is it possible to create such a layout on Pinnight? It seemed to me that FlexLayout is more flexible.


[TestNotAutoLayout.zip](https://github.com/layoutBox/PinLayout/files/2258275/TestNotAutoLayout.zip)

**Comment by sLm-s** [comment]
Everyone has their own pluses. For example, FlexLayout has the choice of the element's compression force. PinLayote has a convenient api. For example, if the text increases, then PinLayout can not cope with his layout but FlexLayout perfectly.

<img width="381" alt="flexlayout" src="https://user-images.githubusercontent.com/20534572/43678821-f68a3310-983b-11e8-86ca-cb39a9d81a32.png">
<img width="376" alt="pinlayout" src="https://user-images.githubusercontent.com/20534572/43678822-f6b5a5e0-983b-11e8-8514-ec521e76f8e2.png">


[ViewController.swift.zip](https://github.com/layoutBox/PinLayout/files/2259665/ViewController.swift.zip)

**Comment by lucdion** [comment]
You're right @sLm-s that this kind of layout better fit FlexLayout, with PinLayout it requires more calculation 🙂
