### ISSUE TITLE
Use with readableContentGuide

### ISSUE THREAD

**Issue by edwellbrook** [layoutBox/PinLayout#168]
Hey there! 👋

I'm investigating wether I should move a portion of my autolayout code to PinLayout, however am unable to find any documentation around using PinLayout with [`readableContentGuide`](https://developer.apple.com/documentation/uikit/uiview/1622644-readablecontentguide). I can see you offer `pin.safeArea` however no other layout guides.

It'd be amazing to see a helper for `readableContentGuide` and perhaps more usefully, a way of laying out against arbitrary `layoutGuide`s.

Please let me know if I'm going about this the wrong way, or if there's maybe a way of doing this already that I may have missed.

Cheers!

**Comment by edwellbrook** [comment]
@lucdion Amazing. Thank you! Please give me an update here when it's available 😄

**Comment by lucdion** [comment]
@edwellbrook, there is a new (release 1.8.2)[https://github.com/layoutBox/PinLayout/releases/tag/1.8.20] that adds a new `pin.readableMargins` property. See the [documentation](https://github.com/layoutBox/PinLayout#safeAreaInsets)

**Comment by edwellbrook** [comment]
This is great! Thanks so much @lucdion 🎉
