### ISSUE TITLE
SizeCalculable with multiplier

### ISSUE THREAD

**Issue by VincentSit** [layoutBox/PinLayout#171]
In Auto Layout, we can easily specify the multiplier of the size of a view, which is very useful for expanding the response range of small buttons. It would be great if there is a similar implementation in Pinlayout.

The possible API is similar to one of the following.

```swift
    pin.sizeToFit(multiplier: 1.5) // both
    pin.sizeToFit(multiplier: (width: 1.5, height: 2.0))
    pin.sizeToFit(multiplier: [.width(1.5), .height(2.0)])
    pin.sizeToFit(multiplier: .width(1.5))
    pin.sizeToFit(.widthFlexible, multiplier: 1.5)
    ...
```

**Comment by VincentSit** [comment]
I have a simple [implementation](https://github.com/VincentSit/PinLayout/tree/multiplier), but I haven't had time to test it. I suddenly have something urgent to deal with.

**Comment by lucdion** [comment]
Hi @VincentSit, this is an edge case from my point of view. I don't see many cases where this would be helpful.

If a button must be bigger, it would make sense to create a subclass of this Button with a method `sizeThatFits()` that returns a bigger size. 

Another solution is to have an overloaded method `point(inside point: CGPoint, with event: UIEvent?)`  that respond to a larger zone. Here is an example of this strategy: https://github.com/mirego/taylor-ios/blob/master/Taylor/UI/ExtendedButton.swift

If you have other cases where a multiplier would be helpful, I may reconsider that decision.

Thanks for your proposal 👍

**Comment by lucdion** [comment]
Another solution, less elegant but:

```
let buttonSize = button.sizeThatFits(CGSize(width: 400, height: .greatest))
let inflatedSize = CGSize(width: buttonSize.width * 1.5, height: buttonsSize.height * 1.5)
button.pin.size(inflatedSize)
```

**Comment by VincentSit** [comment]
I can not tell other usage scenarios at the moment. This requirement may be too personal. Thanks for your advice, I think it can now close this issue.

**Comment by lucdion** [comment]
Thanks @VincentSit, I'm always interested to get input from developers 👍
