### ISSUE TITLE
demo WrapContentView

### ISSUE THREAD

**Issue by ChendayUP** [layoutBox/PinLayout#174]

**Comment by ChendayUP** [comment]
```
        // not work
//        middleLabel.pin.top(30).left().right().sizeToFit(.width)
        // not work
//        middleLabel.pin.top(30).left().width(100%).sizeToFit(.width)
        middleLabel.pin.top(30).left().width(300).sizeToFit(.width)

        button2.pin.below(of: middleLabel, aligned: .center).marginTop(padding)
        button1.pin.before(of: button2, aligned: .center).marginRight(padding)
        button3.pin.after(of: button2, aligned: .center).marginLeft(padding)
// change container
        middleContainer.pin.wrapContent(.vertically, padding: 4).below(of: separatorView1).right().left().marginTop(padding)
```
when i change this code, i find this code not work
`middleLabel.pin.top(30).left().right().sizeToFit(.width)`
`middleLabel.pin.top(30).left().width(100%).sizeToFit(.width)`
only this code work
`middleLabel.pin.top(30).left().width(300).sizeToFit(.width)`

**Comment by lucdion** [comment]
@ChendayUP this is because the width of the parent of middleLabel  (superview) hasn’t been set yet. 

So all methods that refer to the size of the parent, won’t work (right(), width(100%). For these methods to behave as expected, you should set the parent’s width/size.

**Comment by lucdion** [comment]
You probably need to do something like:
```
container.pin.top().horizontally()
middleLabel.pin.top(30).left().right().sizeToFit(.width)
```

**Comment by lucdion** [comment]
I suppose the issue has been fixed
