### ISSUE TITLE
Xcode 10: Module compiled with Swift 4.1.2 cannot be imported by the Swift 4.2 compiler ?

### ISSUE THREAD

**Issue by dillidon** [layoutBox/PinLayout#176]
<img width="605" alt="2018-09-25 22 17 02" src="https://user-images.githubusercontent.com/7115804/46037447-cabfb900-c110-11e8-8389-30c347592c7a.png">

**Comment by lucdion** [comment]
@dillidon if you are using carthage, you need to delete the `Carthage` directory and re-update.
Also, you may need to clean Xcode derived data directory.

**Comment by gssdromen** [comment]
just rerun `carthage update`

**Comment by dillidon** [comment]
@lucdion @gssdromen THX

**Comment by garsdle** [comment]
I think I'm having a similar issue where it is asking me to update PinLayout to 4.2? I'm using cocoa pods though

**Comment by garsdle** [comment]
Yes. Thank you so much luc! Love your framework.
