### ISSUE TITLE
.sizeToFit(.widthFlexible) sometimes exceeds max width

### ISSUE THREAD

**Issue by hueynews** [layoutBox/PinLayout#196]
I have a 1-line label that I need to size. I'd like it to be sized smaller if the text doesn't take up the allowed width, so I use .sizeToFit(.widthFlexible). However, this will give the label its full size, causing it not to truncate.

Is this the expected behavior? I would have expected the label to be sized smaller if possible, but still not overflow its allowed size.

```swift
let label = UILabel()
label.text = "blah blah blah blah"
label.pin.top().horizontally(20).sizeToFit(.widthFlexible)  
// label is sized beyond (superview.width - 2*20)
```

It looks like in [computeSizeToFit](https://github.com/layoutBox/PinLayout/blob/21a657a64bbcf1921b0740342bccd79a16001815/Sources/Impl/PinLayout%2BLayouting.swift#L274), the following line:

```swift
size.width = adjustSizeType.isFlexible ? sizeThatFits.width : fitWidth
```

could instead be:

```swift
size.width = adjustSizeType.isFlexible ? min(fitWidth, sizeThatFits.width) : fitWidth
```

(and the same for height).

Is this the intended behavior? Or am I misunderstanding how .widthFlexible is meant to be used?

**Comment by lucdion** [comment]
@hueynews I understand your situation. This is a really weird behaviour from `UILabel.sizeThatFits()` that returns a width wider than the specified width for a single line label. With a multiline label, it works correctly 😏

Your proposition makes sense to fix this UILabel issue. In the short term, you can use  `.maxWidth(superview.width - 2 * 20)`, which is not as nice.
