### ISSUE TITLE
PinLayout crashes when stepping through breakpoints

### ISSUE THREAD

**Issue by marwanf1** [layoutBox/PinLayout#198]
When having breakpoints PinLayout is crashing whenever I continue execution or perform a step over. The crash happens in `PinLayout+Coordinates.swift`.

```
objc[35942]: Class _TtGC9PinLayout12EdgeListImplCSo6UIView_ is implemented in both ?? (0x7f99680dd9d8) and ?? (0x7f99680dee90). One of the two will be used. Which one is undefined.
objc[35942]: Class _TtGC9PinLayout16VerticalEdgeImplCSo6UIView_ is implemented in both ?? (0x7f99680ddbb8) and ?? (0x7f99680df070). One of the two will be used. Which one is undefined.
Could not cast value of type 'PinLayout.VerticalEdgeImpl<__C.UIView>' (0x7f99680df070) to 'PinLayout.VerticalEdgeImpl<__C.UIView>' (0x7f99680ddbb8).
2019-08-17 19:46:40.203278+0300 Anghami[35942:5847903] Could not cast value of type 'PinLayout.VerticalEdgeImpl<__C.UIView>' (0x7f99680df070) to 'PinLayout.VerticalEdgeImpl<__C.UIView>' (0x7f99680ddbb8).
```

**Comment by lucdion** [comment]
@marwanf1, this is pretty weird.  Which version of Xcode? Which version of iOS?

**Comment by marwanf1** [comment]
@lucdion latest version of Xcode 10.3 and iOS 12.4 though it was happening on pre-iOS 12.4 too. PinLayout is added via Carthage and not Pods, don't know if that matters. Also, it's being used in a large codebase that's a mix of Objective-C and Swift.

**Comment by marwanf1** [comment]
The problem was on our end. Something to do with integrating carthage libs and simulator builds. Sorry for the inconvenience.

**Comment by lucdion** [comment]
No problems, happy to hear that it is not an issue in PinLayout. 
Thanks for the feedback.
