### ISSUE TITLE
How can vCenter the relative view offset?

### ISSUE THREAD

**Issue by HParis** [layoutBox/PinLayout#199]
How can I cover the AutoLayout like below to PinLayout.

```
let view1 = UIView()
let view2 = UIView()
addSubview(view1)
addSubview(view2)
        
view1.centerXAnchor.constraint(equalTo: view2.centerYAnchor, constant: -20)
view1.widthAnchor.constraint(equalTo: view2.widthAnchor, constant: -20)
```

**Comment by lucdion** [comment]
What are you trying to achieve exactly @HParis? It would helps me to give you the best solution.

**Comment by HParis** [comment]
> What are you trying to achieve exactly @HParis? It would helps me to give you the best solution.

![image](https://user-images.githubusercontent.com/4798443/63362027-c6912f80-c3a3-11e9-9830-94bc04b23b74.png)

The viewA's width is 80% relate the superview.

And how can I set the viewB's width is less than the width of viewA, like 20px?

**Comment by iWECon** [comment]
```swift
import PinLayout

// ...

view1.pin.width（80%）
view2.pin.width（view1.frame.width * 0.8）
```

**Comment by lucdion** [comment]
Very old topic. Closing it, sorry
