### ISSUE TITLE
.leading & .trailing?

### ISSUE THREAD

**Issue by Kaakati** [layoutBox/PinLayout#203]
How does this handles .leading & .trailing instead of .left & .right ?

**Comment by lucdion** [comment]
See the doc section https://github.com/layoutBox/PinLayout#rtl_support. Many methods support right-to-left layout.

In this documentation all methods that support RTL languages are marked using the following icon: <img width="36" alt="image" src="https://user-images.githubusercontent.com/14981341/68212415-78092f80-ffa7-11e9-986a-f693684f0fb9.png">
