### ISSUE TITLE
Update to Swift 5.1

### ISSUE THREAD

**Issue by MaruthiBasava** [layoutBox/PinLayout#204]

**Comment by lucdion** [comment]
There is nothing to do for Swift 5.1. Do you have any issue with Xcode 11.1?

**Comment by antoinelamy** [comment]
@lucdion not sure if it's related to this issue but the podspec is still pointing to Swift 4.2

**Comment by lucdion** [comment]
Thanks @antoinelamy, I've updated to podspec to specify swift versions ['4.2', '5.0', '5.1']

@MaruthiBasava New release 1.8.12
https://github.com/layoutBox/PinLayout/releases/tag/1.8.12
