### ISSUE TITLE
Validate functions handle NaNs incorrectly

### ISSUE THREAD

**Issue by own2pwn** [layoutBox/PinLayout#205]
I know that most of the time `NaN`s are passed to PinLayout from "user space". But I believe that validate<> functions (validateWidth, validateHeight, etc) handle them incorrectly. 
Neither `CGFloat.nan < 0` nor `CGFloat.nan > 0` will return true so the check will pass. 

What do you think about rewrite the checks in some kind of this way:
```
guard width.isZero || width.isNormal else {
    warnWontBeApplied("the width (\(width)) must be greater than or equal to zero.", context)
    return false
}
return true
```

**Comment by lucdion** [comment]
You're right, I will open a PR that fixes that.

**Comment by lucdion** [comment]
Related PR https://github.com/layoutBox/PinLayout/pull/206

**Comment by lucdion** [comment]
https://github.com/layoutBox/PinLayout/releases/tag/1.8.11
