### ISSUE TITLE
center and sizeToFit

### ISSUE THREAD

**Issue by tcurdt** [layoutBox/PinLayout#207]
I am a little confused on the `sizeToFit`

```
text.pin.center().sizeToFit()
```

When the text changes and a `layout()` is called the previous width is kept.

So I tried with `.content` but it seems like specifying a width is the only way to get it at least somewhat working:

```
 text.pin.center().width(50%).sizeToFit(.widthFlexible)
```

I feel like don't quite understand the restrictions of `sizeToFit` yet. Reading the README it sounds like `center().sizeToFit()` should be enough.

**Comment by lucdion** [comment]
I agree that it is not that clear what is the behaviour of this method, at the end, it is equivalent to:
```
label.frame.size = label.sizeThatFits(CGSize(width: label.frame.width, height: label.frame.height))
```

So that may not be what you wanted, the solution may be to call `label.sizeToFit()` when you update the UILabel's text, and then just call `label.pin.center()` in `layoutSubViews()`.

**Comment by tcurdt** [comment]
Thanks for the help. Indeed calling `label.sizeToFit` after the value assignment seems to do the trick.
Would be great to add these details to the docs somehow. 
But from my side feel free to close.
Thanks!
