### ISSUE TITLE
Cocoapods v1.8.4 environment cannot be installed, pod install Other resource libraries are possible.

### ISSUE THREAD

**Issue by KBvsMJ** [layoutBox/PinLayout#211]
Cocoapods v1.8.4 environment cannot be installed, pod install Other resource libraries are possible.
![image](https://user-images.githubusercontent.com/8489350/68538744-68795480-03b4-11ea-805f-ed6378a194e1.png)

**Comment by lucdion** [comment]
What do you mean by cocoapods 1.8.4 cannot be installed? I can install it on my mac without any issues? Maybe I don't understand your problem 🤔

**Comment by KBvsMJ** [comment]
@lucdion   can't pod install
![image](https://user-images.githubusercontent.com/8489350/68766166-52d88900-0659-11ea-8b6d-fe25f1b49b0d.png)

**Comment by lucdion** [comment]
Does it works with other pods?
Here a few possible solutions:
* https://stackoverflow.com/questions/36279534/pod-setup-cloning-into-master-error-rpc-failed-result-56-http-code-200
* https://github.com/CocoaPods/CocoaPods/issues/5592
* https://github.com/CocoaPods/CocoaPods/issues/7025

**Comment by lucdion** [comment]
Closing this issue, no user's feedback for quite a while.
