### ISSUE TITLE
`SWIFT_VERSION` error in Cocoapods

### ISSUE THREAD

**Issue by xilin** [layoutBox/PinLayout#213]
When I specify 1.8.3 as my dependency in a podspec file, `pod install` give me the following error:

```
[!] Unable to determine Swift version for the following pods:

- `PinLayout` does not specify a Swift version and none of the targets (`XXX_Example`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.
```

Since we just remove version range in last [release](https://github.com/layoutBox/PinLayout/commit/b1b2583fadc851051587c8aef9cc084301f31999).

Can we keep the version setting using something like [version range](https://github.com/groue/GRDB.swift/issues/410)?

Thanks.

**Comment by lucdion** [comment]
This has been fixed. Cocoapod now specify a range of version from 4.2 to 5.*
