### ISSUE TITLE
Order of constraints

### ISSUE THREAD

**Issue by MarcoCadei** [layoutBox/PinLayout#214]
When layouting a view is there a "recommended" order in which to write the constraints, based on internal working of PinLayout itself?
e.g. it is better to set size first, then position, etc...

**Comment by lucdion** [comment]
The order doesn't have any effect on the performance nor the result. 

You can check the section "PinLayout style guide" in the README for some tips regarding coding style: https://github.com/layoutBox/PinLayout#pinlayout-style-guide
