### ISSUE TITLE
Need example support

### ISSUE THREAD

**Issue by ankitthakur** [layoutBox/PinLayout#226]
Hi team,
I am learning Pinlayout about how it works. I am having multiple elements in the table cell and can dynamically be added or removed. Right now I have achieved it with UIStackView add/insertArrangedViews. How we can achieve the same with Pinlayout. Please suggest. 
For Example:
I am having a vertical stack view where 3 views are added and the 3rd one is a horizontal stack view. Now I am inserting 1 new view at index 0 of the vertical stack view. 
Then I am doing 2 tasks together:
1 Adding a new element in the 3rd stack view (Horizontal stack view)
2. Removed 1st element (index 1) from the Vertical stack view.

**Comment by lucdion** [comment]
Very old topic. Closing it, sorry
