### ISSUE TITLE
no percent on macOS?

### ISSUE THREAD

**Issue by tcurdt** [layoutBox/PinLayout#236]
In an AppKit project I am doing

```
import PinLayout
...
layer.pin.width(50%)
```

but that is giving me

```
Cannot convert value of type 'PinLayout<CALayer>' to expected argument type 'Int'
```

From the code I don't see why this wouldn't work.
Any pointers?

**Comment by protosse** [comment]
![图片](https://user-images.githubusercontent.com/30048222/150897496-68626ebd-f70d-47c5-a2b1-d899bf679aaf.png)
I have a try just moment, it works well

**Comment by tcurdt** [comment]
I haven't changed a thing and now it seems to work here, too. Sorry, about that.
I guess Xcode just was in a mood.
Thanks for trying.
