### ISSUE TITLE
How do I auto-size the container of image view and label?

### ISSUE THREAD

**Issue by KhazanGu** [layoutBox/PinLayout#247]
I wanna a view containing an imageView and a label. But I don't know how to auto size the container. Because the number of lines with the label are undecided in the different devices. Please help me.

```
        self.imageView.pin.width(48).height(48).vCenter()
        self.label.pin.below(of: self.imageView).left(20).right(20).sizeToFit(.width)
        self.containerView.pin.wrapContent().center()
```

**Comment by KhazanGu** [comment]
Hi, Thanks a lot. This is the design of the question.

<img width="336" alt="Screen Shot 2022-02-16 at 10 54 32" src="https://user-images.githubusercontent.com/14102044/154188002-1be3acd2-8807-4629-8360-8ac9b2923e4a.png">

The designer requested the imageView and the label should at the view center. So I defined a container with an imageView and a label, I just have no idea to auto-size the container. Thanks again.

**Comment by lucdion** [comment]
Any feedback? Else, please close this issue.

**Comment by KhazanGu** [comment]
I'm so sorry about not responding for a long time. Because of something I asked for leave, I will check it after that.  Thank you a lot.
