### ISSUE TITLE
invalid parameter not satisfying: !cgsizeequaltosize(size, cgsizezero)

### ISSUE THREAD

**Issue by wjling** [layoutBox/PinLayout#248]
I use `UICollectionViewCompositionalLayout` to layout my collectionView. I have a custom cell A and a custom view B. Cell A's contentView adds B as a subview. Both cell A and view B has `autoSizeThatFits` in method `sizeThatFits`. But I get an exception when I enter the viewController said `invalid parameter not satisfying: !cgsizeequaltosize(size, cgsizezero)`. If I remove `autoSizeThatFits` code and it runs without exception. I can't figure out where is wrong.

**Comment by antoinelamy** [comment]
Can you reproduce the issue in a sample project and post it here? It would be a lot easier to troubleshoot.

**Comment by wjling** [comment]
@antoinelamy I make a demo and you can check it. I write some comments in code to describe the situation
[TestPinLayout.zip](https://github.com/layoutBox/PinLayout/files/8151567/TestPinLayout.zip)
s

**Comment by protosse** [comment]
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/30048222/157377511-b6f56f14-71cf-4ca7-aa8d-1c422fb28379.png">
I don't know if it is right, but it runs without exception.

**Comment by wjling** [comment]
<img width="1497" alt="image" src="https://user-images.githubusercontent.com/4201777/157389983-3c6cbe0e-0603-442d-8c2e-b9c80ef022e9.png">
Weired. I crashes like this. I'm using Xcode 13.2.1, simulator iOS 15.2

**Comment by lucdion** [comment]
I've found this answer: https://stackoverflow.com/a/64767502/4342765
> It was just because I forgot to set translatesAutoresizingMaskIntoConstraints to false for a subview I was adding to cell's contentView...

Could it be this?

**Comment by jsyrtsov** [comment]
You can't call autosizethatfits in UICollectionViewCell. I got the same errors while calling it so.
I found another solution to create autosizing cells in collection view.

**Comment by wjling** [comment]
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/4201777/157581677-b7dbf0b6-84e7-4988-a180-33f63110cec5.png">


No luck. Still crashes

> I've found this answer: https://stackoverflow.com/a/64767502/4342765
> 
> > It was just because I forgot to set translatesAutoresizingMaskIntoConstraints to false for a subview I was adding to cell's contentView...
> 
> Could it be this?
