### ISSUE TITLE
Can I use autoSizeThatFits on collection view cell ? 

### ISSUE THREAD

**Issue by jsyrtsov** [layoutBox/PinLayout#249]
Hello, thanks in advance ! 

I want to create a UICollectionViewCell with some labels added below each other. 

+------------------------+
|                                           |
|               Label                   |
|                                           |
|               Label                   |
|                                           |
|               Label                   |
+------------------------+

So my cell should calculate the height of itself. 
Can you please help me with that case ?

**Comment by jsyrtsov** [comment]
I think I found solution, if anybody interested I can share my code with auto sizing cells in collection view using PinLayout

**Comment by antoinelamy** [comment]
> I think I found solution, if anybody interested I can share my code with auto sizing cells in collection view using PinLayout

Sure, it may help some wanting to achieve the same thing.

**Comment by jsyrtsov** [comment]
> > I think I found solution, if anybody interested I can share my code with auto sizing cells in collection view using PinLayout
> 
> Sure, it may help some wanting to achieve the same thing.

What is the best way to share some code? Should I add it to example app and create PR or just create zip and leave here the link ?

**Comment by antoinelamy** [comment]
I’d drop a zip here
