### ISSUE TITLE
Can I let View A cover B half?

### ISSUE THREAD

**Issue by tanpengsccd** [layoutBox/PinLayout#252]
<img width="441" alt="image" src="https://user-images.githubusercontent.com/13959880/175827076-f33af085-854c-49fe-a667-0cc8b03d3816.png">
like this .

**Comment by tanpengsccd** [comment]
I tried 
```
 view.addSubview(A)
view.addSubview(B)
A.pin.top().left().right()
btnContainer.pin.top(B.edge.top).left(to: B.edge.left).right(to: B.edge.right)
```

but it not work. just list A,B vetically.

**Comment by antoinelamy** [comment]
Your code snippet is a little bit confusing but yes you can. I would recommend taking a look at pinning view edges in the readme. You just need to pin B top edge to A vCenter edge.

https://github.com/layoutBox/PinLayout#pinlayout-uiviews-edges
