### ISSUE TITLE
Document missing link

### ISSUE THREAD

**Issue by faithinker** [layoutBox/PinLayout#271]
https://github.com/layoutBox/PinLayout/blob/master/docs/PinLayout_principles.md

PinLayout exist to be simple and fast as possible! In fact, it is fast as manual layouting. See [performance results below.](https://github.com/layoutBox/PinLayout/blob/master/docs/PinLayout_principles.md#performance)

When I click  "performance results below."  link, it  doesn't work.
The #performance tag doesn't navigate to the page.

Please check it out.

**Comment by lucdion** [comment]
Thanks, I have fixed it
